org: bernardi
app: paga-leve-react
name: react-starter
component: website

provider:
  name: aws
  stage: dev
  environment:
    REACT_APP_API_URL: 'https://v3b2slwkhg.execute-api.us-east-1.amazonaws.com/dev'

inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
